import type { Metadata } from "next";
import { Geist, Geist_Mono, Montserrat } from "next/font/google";
import "./globals.css";
import Footer from "./components/Footer";
import NavBar from "./components/NavBar";
import ClientProvider from "./utils/ClientProvider";
import Spinner from "./components/Spinner";
import SplashLoader from "./components/SplashLoader";
import { Suspense } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  //variable: '--font-montserrat',
  subsets: ['latin'],
  display: 'swap',
  //weight: ['400', '500', '600', '700'], // Choose the weights you need
});

export const metadata: Metadata = {
  title: "Bloocode",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className} antialiased`}
      >
        <ClientProvider>
          <Suspense fallback={<Spinner />}>
            <NavBar />
            {children}
            <Footer />
          </Suspense>
        </ClientProvider>
      </body>
    </html>
  );
}
